// Code generated by hertz generator.

package handler

import (
	"context"
	"fmt"
	"mime/multipart"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	publish "mini-tiktok-backend/cmd/api/biz/model/api/publish"
)

type Paras struct {
	data  *multipart.FileHeader `form:"data"`
	token string                `form:"token"`
	title string                `form:"title"`
}

// DouyinPublishAction .
// @router /douyin/publish/action/ [POST]
func DouyinPublishAction(ctx context.Context, c *app.RequestContext) {
	var err error
	var req Paras
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	fmt.Println(req.token, req.title, req.data)

	resp := new(publish.DouyinPublishActionResponse)

	c.JSON(consts.StatusOK, resp)
}
