// Code generated by hertz generator.

package handler

import (
	"context"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	"mime/multipart"
	api_publish "mini-tiktok-backend/cmd/api/biz/model/api/publish"
	"mini-tiktok-backend/cmd/api/biz/mw"
	"mini-tiktok-backend/cmd/api/biz/rpc"
	"mini-tiktok-backend/kitex_gen/publish"
)

// Paras 文件类型的参数接收单独定义
type Paras struct {
	data  *multipart.FileHeader `form:"data"`
	token string                `form:"token"`
	title string                `form:"title"`
}

// DouyinPublishAction .
// @router /douyin/publish/action/ [POST]
func DouyinPublishAction(ctx context.Context, c *app.RequestContext) {
	var err error
	var req Paras
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	file, err := req.data.Open()
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}
	defer file.Close()

	var fileContent []byte
	if fileContent, err = ReadFileContent(file); err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	user, _ := c.Get("id")

	err = rpc.PublishVideo(ctx, &publish.PublishVideoRequest{
		UserId: user.(*mw.User).UserId,
		Data:   fileContent,
		Title:  req.title,
	})

	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(api_publish.DouyinPublishActionResponse)
	c.JSON(consts.StatusOK, resp)
}

func ReadFileContent(file multipart.File) ([]byte, error) {
	const fileChunkSize = 1 * (1 << 20) // read 1MB each time.
	fileContent := make([]byte, 0, 0)

	for {
		fileChunk := make([]byte, fileChunkSize)
		n, err := file.Read(fileChunk)
		if n == 0 {
			break
		}
		if err != nil {
			return nil, err
		}
		fileChunk = fileChunk[:n]
		fileContent = append(fileContent, fileChunk...)
	}

	return fileContent, nil
}
