// Code generated by hertz generator.

package handler

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	relation "mini-tiktok-backend/cmd/api/biz/model/api/relation"
)

// DouyinRelationFollowerList .
// @router /douyin/relation/follower/list/ [GET]
func DouyinRelationFollowerList(ctx context.Context, c *app.RequestContext) {
	var err error
	var req relation.DouyinRelationFollowerListRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(relation.DouyinRelationFollowerListResponse)

	c.JSON(consts.StatusOK, resp)
}
