// Code generated by hertz generator.

package handler

import (
	"context"
	"github.com/cloudwego/hertz/pkg/common/utils"
	"mini-tiktok-backend/cmd/api/biz/mw"
	"mini-tiktok-backend/cmd/api/biz/rpc"
	"mini-tiktok-backend/kitex_gen/relation"
	pkg_consts "mini-tiktok-backend/pkg/consts"
	"mini-tiktok-backend/pkg/errno"

	"github.com/cloudwego/hertz/pkg/app"
	api_relation "mini-tiktok-backend/cmd/api/biz/model/api/relation"
)

// DouyinRelationFollowerList .
// @router /douyin/relation/follower/list/ [GET]
func DouyinRelationFollowerList(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api_relation.DouyinRelationFollowerListRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		SendResponse(c, err, utils.H{})
		return
	}

	user, _ := c.Get(pkg_consts.IdentityKey)

	userList, err := rpc.GetFollowerList(ctx, &relation.GetFollowerListRequest{
		UserId:       user.(*mw.User).UserId,
		TargetUserId: req.UserID,
	})
	if err != nil {
		SendResponse(c, err, utils.H{})
		return
	}

	SendResponse(c, errno.Success, utils.H{
		"user_list": userList,
	})
}
