// Code generated by hertz generator.

package handler

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	favorite "mini-tiktok-backend/cmd/api/biz/model/api/favorite"
)

// DouyinFavoriteList .
// @router /douyin/favorite/list/ [GET]
func DouyinFavoriteList(ctx context.Context, c *app.RequestContext) {
	var err error
	var req favorite.DouyinFavoriteListRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(favorite.DouyinFavoriteListResponse)

	c.JSON(consts.StatusOK, resp)
}
