// Code generated by hertz generator.

package handler

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	relation "mini-tiktok-backend/cmd/api/biz/model/api/relation"
)

// DouyinRelationFollowList .
// @router /douyin/relation/follow/list/ [GET]
func DouyinRelationFollowList(ctx context.Context, c *app.RequestContext) {
	var err error
	var req relation.DouyinRelationFollowListRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(relation.DouyinRelationFollowListResponse)

	c.JSON(consts.StatusOK, resp)
}
