package consts

const (
	UserTableName       = "users"
	VideoTableName      = "videos"
	FavoriteTableName   = "favorites"
	CommentTableName    = "comments"
	RelationTableName   = "relations"
	SecretKey           = "secret key"
	IdentityKey         = "id"
	UserIdKey           = "user_id"
	MySQLDefaultDSN     = "gorm:gorm@tcp(localhost:9910)/gorm?charset=utf8&parseTime=True&loc=Local"
	OSSEndPoint         = "oss-cn-beijing.aliyuncs.com"
	AccessKeyId         = "LTAI5tBQzy3pKUKA1juX68Mq"
	AccessKeySecret     = "iNWQt90rnVTZJYENX4EDWZSUfNDtBu"
	OSSBucketName       = "mini-tiktok-backend"
	OSSResourceURL      = "https://mini-tiktok-backend.oss-cn-beijing.aliyuncs.com/"
	TCP                 = "tcp"
	ETCDAddress         = "127.0.0.1:2379"
	ApiServiceName      = "api"
	UserServiceName     = "user"
	PublishServiceName  = "publish"
	FavoriteServiceName = "favorite"
	VideoServiceName    = "video"
	CommentServiceName  = "comment"
	ApiServiceAddr      = "0.0.0.0:8080"
	UserServiceAddr     = "127.0.0.1:8081"
	PublishServiceAddr  = "127.0.0.1:8082"
	FavoriteServiceAddr = "127.0.0.1:8083"
	VideoServiceAddr    = "127.0.0.1:8084"
	CommentServiceAddr  = "127.0.0.1:9090"
)
